//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviePortal.v1._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieFoundEntities : DbContext
    {
        public MovieFoundEntities()
            : base("name=MovieFoundEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MovieInfo1> MovieInfo1 { get; set; }
        public virtual DbSet<MovieInfoes_NewTV> MovieInfoes_NewTV { get; set; }
        public virtual DbSet<MovieInfoes_PopularMovieInfo> MovieInfoes_PopularMovieInfo { get; set; }
        public virtual DbSet<MovieInfoes_ReleaseMovie> MovieInfoes_ReleaseMovie { get; set; }
        public virtual DbSet<MovieInfoes_TopTV> MovieInfoes_TopTV { get; set; }
        public virtual DbSet<MovieInfoes_WatchList> MovieInfoes_WatchList { get; set; }
    }
}
