//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviePortal.v1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieInfoes_TopTV
    {
        public int Id { get; set; }
    
        public virtual MovieInfo1 MovieInfo { get; set; }
    }
}
